from .knowledge import (
    RateProxyView,
    PromptProxyView,
    KnowledgeProxyView,
    KnowledgeUploadProxyView,
    KnowledgeDetailProxyView,
)
from .products import (
    ProductTemplateProxyView,
    ProductUploadProxyView,
    ProductExportProxyView,
    ProductUploadJobDetailProxyView,
    ProductUploadJobListProxyView,
    ProductFilterProxyView,
    ProductListProxyView,
    ProductDetailProxyView,
    ProductRestoreProxyView,
    ProductStatusProxyView,
    ProductBulkStatusProxyView,
    ProductFlagsProxyView,
    ProductBulkFlagsProxyView,
    ProductEmbeddingRefreshProxyView,
)
from .catalog import (
    CategoryListCreateProxyView,
    CategoryDetailsProxyView,
    BrandListCreateProxyView,
    BrandDetailsProxyView,
    SubcategoryListCreateProxyView,
    SubcategoryDetailsProxyView,
)
from .recommendations import (
    AIRecommendProxyView,
    AISearchProxyView,
    AISimilarProxyView,
    AICrossSellProxyView,
    AIUpsellProxyView,
    AISkincareProxyView,
    AIFragranceProxyView,
    AIPersonalisedProxyView,
)
from .embeddings import (
    AIEmbeddingStatusProxyView,
    AIEmbeddingTriggerProxyView,
)
from .events import ProductEventProxyView
from .sync import SapSyncProxyView

__all__ = [
    "RateProxyView",
    "PromptProxyView",
    "KnowledgeProxyView",
    "KnowledgeUploadProxyView",
    "KnowledgeDetailProxyView",
    "ProductTemplateProxyView",
    "ProductUploadProxyView",
    "ProductUploadJobDetailProxyView",
    "ProductUploadJobListProxyView",
    "ProductFilterProxyView",
    "ProductListProxyView",
    "ProductDetailProxyView",
    "ProductRestoreProxyView",
    "ProductStatusProxyView",
    "ProductBulkStatusProxyView",
    "ProductFlagsProxyView",
    "ProductBulkFlagsProxyView",
    "ProductEmbeddingRefreshProxyView",
    "CategoryListCreateProxyView",
    "CategoryDetailsProxyView",
    "BrandListCreateProxyView",
    "BrandDetailsProxyView",
    "SubcategoryListCreateProxyView",
    "SubcategoryDetailsProxyView",
    "AIRecommendProxyView",
    "AISearchProxyView",
    "AISimilarProxyView",
    "AICrossSellProxyView",
    "AIUpsellProxyView",
    "AISkincareProxyView",
    "AIFragranceProxyView",
    "AIPersonalisedProxyView",
    "AIEmbeddingStatusProxyView",
    "AIEmbeddingTriggerProxyView",
    "ProductEventProxyView",
    "SapSyncProxyView",
]
