"""
services/excel_export_service.py
=================================
Enterprise Excel export for the Dhifaf Baghdad product catalog.

Import compatibility guarantee
-------------------------------
Every file generated by this service passes POST /products/upload without any
validation error.  Column names in the Excel header row are the exact strings
expected by the upload validator (e.g. "barcode", "brand_name", "item_name").

Export-only columns (price_iqd, stock_status, ai_score, last_synced_sap) are
included for reference.  The upload validator ignores unknown columns, so they
cause no import errors.

Column schema
-------------
Column definitions live in schemas/export_columns.py — the SINGLE source of
truth shared with the upload validator.  Neither this file nor upload.py
re-declares columns independently.

Performance architecture
------------------------
write_only=True (openpyxl)
    Rows are serialised to XML immediately; no in-memory cell grid is kept.
    Memory overhead is constant regardless of dataset size.

yield_per(_CHUNK_SIZE) (SQLAlchemy)
    DB cursor returns results in batches of 500 rows.
    At most 500 product dicts exist in Python RAM at any time.

Single JOIN query
    Brand / Category / Subcategory names resolved up-front via LEFT OUTER JOINs.
    Zero N+1 queries regardless of row count.

Scaling guidance
----------------
< 50k rows   — BytesIO, returned synchronously (~5-15 MB)
50k-500k rows — swap BytesIO for NamedTemporaryFile + FileResponse
> 500k rows   — background job + object-storage presigned URL
"""
from __future__ import annotations

import io
import json
import logging
import os
from typing import Any, Optional

from openpyxl import Workbook
from openpyxl.cell.cell import WriteOnlyCell
from openpyxl.utils import get_column_letter
from sqlalchemy import or_
from sqlalchemy.orm import Session

from models import Brand, Category, Product, ProductSearchIndex, Subcategory
from schemas.export_columns import PRODUCT_IMPORT_EXPORT_COLUMNS, ExportColumn
from utils.excel_styles import (
    ALIGN_HEADER,
    ALIGN_LEFT,
    BORDER_CELL,
    BORDER_HEADER,
    FILL_HEADER,
    FILL_HEADER_RO,
    FILL_LOW_STOCK,
    FILL_OUT_STOCK,
    FILL_ROW_EVEN,
    FILL_ROW_ODD,
    FONT_DATA,
    FONT_HEADER,
)
from schemas.export_columns import FMT_TEXT

logger = logging.getLogger(__name__)

# ── Module-level constants ────────────────────────────────────────────────────
_CHUNK_SIZE  = 500
_TOTAL_COLS  = len(PRODUCT_IMPORT_EXPORT_COLUMNS)
_DATA_START  = 2   # row 1 = header, row 2 = first data row

_RATE_FILE   = os.path.join(os.path.dirname(os.path.dirname(__file__)), "rate.json")

_SORT_COLS: dict[str, tuple[str, str]] = {
    "name_asc":    ("item_name",     "ASC"),
    "name_desc":   ("item_name",     "DESC"),
    "price_asc":   ("price",         "ASC"),
    "price_desc":  ("price",         "DESC"),
    "stock_asc":   ("available_qty", "ASC"),
    "stock_desc":  ("available_qty", "DESC"),
    "created_asc": ("created_at",    "ASC"),
    "created_desc":("created_at",    "DESC"),
}
_SORT_ATTRS = {
    "item_name":     Product.item_name,
    "price":         Product.price,
    "available_qty": Product.available_qty,
    "created_at":    Product.created_at,
}


# ══════════════════════════════════════════════════════════════════════════════
# Internal helpers
# ══════════════════════════════════════════════════════════════════════════════

def _load_iqd_rate() -> float:
    try:
        with open(_RATE_FILE, "r", encoding="utf-8") as f:
            return float(json.load(f).get("iqd_rate", 1310))
    except Exception:
        return 1310.0


def _stock_status(qty: Any) -> str:
    return "in_stock" if qty and int(qty) > 0 else "out_of_stock"


def _mc(
    ws,
    value: Any = None,
    *,
    font=None,
    fill=None,
    alignment=None,
    border=None,
    num_fmt: Optional[str] = None,
) -> WriteOnlyCell:
    """Create a styled WriteOnlyCell."""
    cell = WriteOnlyCell(ws, value=value)
    if font:      cell.font          = font
    if fill:      cell.fill          = fill
    if alignment: cell.alignment     = alignment
    if border:    cell.border        = border
    if num_fmt:   cell.number_format = num_fmt
    return cell


def _row_to_dict(r: Any, rate: float) -> dict:
    """
    Serialise a raw SQLAlchemy multi-column named-tuple row into the standard
    product dict format.

    The dict keys match the `extractor` values defined in ExportColumn for
    simple string keys.  Callable extractors receive this dict directly.

    price / price_iqd preserve None when the DB value is NULL so that empty
    cells in the export do not overwrite existing values on re-import.
    """
    price  = float(r.price) if r.price is not None else None
    tier   = getattr(r, "price_tier",    None)
    stat   = getattr(r, "product_status", None)
    rsco   = getattr(r, "recommendation_score_override", None)
    ai_s   = getattr(r, "ai_score", None)

    return {
        # Identity
        "barcode":           r.barcode,
        "item_code":         r.item_code,
        "item_name":         r.item_name,
        "sap_product_id":    r.sap_product_id,
        # Display
        "description":       r.description,
        "image_url":         r.image_url,
        # AI / Search
        "skin_type":         r.skin_type,
        "concerns":          list(r.concerns or []),
        "tags":              list(r.tags     or []),
        # Pricing — None preserved so empty cell = "don't overwrite" on re-import
        "price":             price,
        "price_iqd":         round(price * rate) if price is not None else None,
        "available_qty":     int(r.available_qty) if r.available_qty is not None else None,
        "stock_status":      _stock_status(r.available_qty),
        # Classification
        "price_tier":        getattr(tier,  "value", tier),
        "brand_family":      getattr(r, "brand_family", None),
        "product_status":    getattr(stat,  "value", stat),
        # Recommendation flags
        "is_best_selling":   bool(r.is_best_selling)      if r.is_best_selling      is not None else False,
        "is_new_arrival":    bool(getattr(r, "is_new_arrival",     None)) if getattr(r, "is_new_arrival",     None) is not None else False,
        "is_recommended":    bool(getattr(r, "is_recommended",     None)) if getattr(r, "is_recommended",     None) is not None else False,
        "is_cod_recommended":bool(getattr(r, "is_cod_recommended", None)) if getattr(r, "is_cod_recommended", None) is not None else False,
        "recommendation_priority":       getattr(r, "recommendation_priority", None),
        "recommendation_score_override": float(rsco) if rsco is not None else None,
        # Legacy
        "best_selling_scope":getattr(r, "best_selling_scope", None),
        "sales_rank":        getattr(r, "sales_rank", None),
        # SAP / AI
        "last_synced_sap":   r.last_synced_sap.isoformat() if r.last_synced_sap else None,
        "ai_score":          float(ai_s) if ai_s is not None else 0.0,
        # Relations (nested dicts — lambdas in ExportColumn extract the name)
        "brand":      {"id": r.brand_id,       "name": getattr(r, "brand_name",       None)},
        "category":   {"id": r.category_id,    "name": getattr(r, "category_name",    None)},
        "subcategory":{"id": r.subcategory_id, "name": getattr(r, "subcategory_name", None)},
    }


# ══════════════════════════════════════════════════════════════════════════════
# Query builder  (mirrors ProductRepository.list_products — NO pagination)
# ══════════════════════════════════════════════════════════════════════════════

def _build_export_query(
    db:              Session,
    *,
    q:               Optional[str]   = None,
    brand_id:        Optional[int]   = None,
    category_id:     Optional[int]   = None,
    subcategory_id:  Optional[int]   = None,
    is_best_selling: Optional[int]   = None,
    in_stock:        Optional[bool]  = None,
    min_price:       Optional[float] = None,
    max_price:       Optional[float] = None,
    product_status:  Optional[str]   = None,
    sort_by:         Optional[str]   = "created_desc",
):
    sort_col, sort_dir = _SORT_COLS.get(
        sort_by or "created_desc", ("created_at", "DESC")
    )

    select_cols = [
        Product.barcode,            Product.item_code,          Product.item_name,
        Product.sap_product_id,     Product.description,        Product.image_url,
        Product.skin_type,          Product.concerns,           Product.tags,
        Product.price,              Product.available_qty,
        Product.price_tier,         Product.brand_family,       Product.product_status,
        Product.is_best_selling,    Product.is_new_arrival,
        Product.is_recommended,     Product.is_cod_recommended,
        Product.recommendation_priority,    Product.recommendation_score_override,
        Product.best_selling_scope, Product.sales_rank,
        Product.price_source_override,      Product.last_synced_sap,
        Product.ai_score,
        Product.brand_id,           Product.category_id,        Product.subcategory_id,
        Brand.name.label("brand_name"),
        Category.name.label("category_name"),
        Subcategory.name.label("subcategory_name"),
    ]

    query = (
        db.query(*select_cols)
        .join(Brand,       Brand.id       == Product.brand_id,       isouter=True)
        .join(Category,    Category.id    == Product.category_id,    isouter=True)
        .join(Subcategory, Subcategory.id == Product.subcategory_id, isouter=True)
        .filter(Product.deleted_at.is_(None))
    )

    if q:
        query = query.join(
            ProductSearchIndex,
            ProductSearchIndex.product_id == Product.barcode,
            isouter=True,
        )
        like = f"%{q.strip().lower()}%"
        query = query.filter(
            or_(
                ProductSearchIndex.search_text.ilike(like),
                Product.item_name.ilike(f"%{q.strip()}%"),
            )
        )

    if brand_id        is not None: query = query.filter(Product.brand_id        == brand_id)
    if category_id     is not None: query = query.filter(Product.category_id     == category_id)
    if subcategory_id  is not None: query = query.filter(Product.subcategory_id  == subcategory_id)
    if is_best_selling is not None: query = query.filter(Product.is_best_selling == is_best_selling)
    if in_stock:                    query = query.filter(Product.available_qty    >  0)
    if min_price       is not None: query = query.filter(Product.price            >= min_price)
    if max_price       is not None: query = query.filter(Product.price            <= max_price)
    if product_status  is not None: query = query.filter(Product.product_status   == product_status)

    attr = _SORT_ATTRS.get(sort_col, Product.created_at)
    query = query.order_by(attr.desc() if sort_dir == "DESC" else attr.asc())
    return query


# ══════════════════════════════════════════════════════════════════════════════
# Workbook writers
# ══════════════════════════════════════════════════════════════════════════════

def _write_header_row(ws) -> None:
    """
    Write row 1: styled column headers.

    Import-compatible columns  → dark navy background (C_HEADER_BG)
    Export-only columns        → medium navy background (C_HEADER_RO)

    Both use bold white text — visually consistent yet subtly distinguishable.
    """
    cells = []
    for col in PRODUCT_IMPORT_EXPORT_COLUMNS:
        fill = FILL_HEADER if col.import_compatible else FILL_HEADER_RO
        cells.append(_mc(
            ws, col.name,
            font=FONT_HEADER,
            fill=fill,
            alignment=ALIGN_HEADER,
            border=BORDER_HEADER,
        ))
    ws.append(cells)


def _write_data_row(ws, seq: int, row_dict: dict, is_odd: bool) -> None:
    """
    Write one product data row with conditional stock-level coloring.

    Stock coloring (highest priority first):
      out_of_stock    → FILL_OUT_STOCK  (soft red)
      qty 1–5         → FILL_LOW_STOCK  (amber warning)
      odd row         → FILL_ROW_ODD    (light blue stripe)
      even row        → FILL_ROW_EVEN   (white)
    """
    qty    = row_dict.get("available_qty")
    status = row_dict.get("stock_status", "out_of_stock")

    if status == "out_of_stock":
        row_fill = FILL_OUT_STOCK
    elif qty is not None and 0 < qty <= 5:
        row_fill = FILL_LOW_STOCK
    elif is_odd:
        row_fill = FILL_ROW_ODD
    else:
        row_fill = FILL_ROW_EVEN

    cells: list[WriteOnlyCell] = []
    for col in PRODUCT_IMPORT_EXPORT_COLUMNS:
        if col.extractor == "__row_num__":
            value: Any = seq
        elif callable(col.extractor):
            value = col.extractor(row_dict)
        else:
            value = row_dict.get(col.extractor)

        # Coerce None to empty string for text columns (Excel shows blank, not "None")
        if value is None and col.num_fmt == FMT_TEXT:
            value = ""

        cells.append(_mc(
            ws, value,
            font=FONT_DATA,
            fill=row_fill,
            alignment=ALIGN_LEFT,
            border=BORDER_CELL,
            num_fmt=col.num_fmt,
        ))
    ws.append(cells)


# ══════════════════════════════════════════════════════════════════════════════
# Public API
# ══════════════════════════════════════════════════════════════════════════════

def generate_export_bytes(
    db:              Session,
    *,
    q:               Optional[str]   = None,
    brand_id:        Optional[int]   = None,
    category_id:     Optional[int]   = None,
    subcategory_id:  Optional[int]   = None,
    is_best_selling: Optional[int]   = None,
    in_stock:        Optional[bool]  = None,
    min_price:       Optional[float] = None,
    max_price:       Optional[float] = None,
    product_status:  Optional[str]   = None,
    sort_by:         Optional[str]   = "created_desc",
) -> tuple[io.BytesIO, int]:
    """
    Build the complete Excel workbook and return (buffer, rows_written).

    The returned buffer is seeked to position 0 and ready for streaming.

    The file is guaranteed to pass POST /products/upload without any
    "Missing required columns" error because column headers use the exact
    names from REQUIRED_UPLOAD_COLUMNS in schemas/export_columns.py.
    """
    rate     = _load_iqd_rate()
    export_q = _build_export_query(
        db,
        q=q, brand_id=brand_id, category_id=category_id,
        subcategory_id=subcategory_id, is_best_selling=is_best_selling,
        in_stock=in_stock, min_price=min_price, max_price=max_price,
        product_status=product_status, sort_by=sort_by,
    )

    logger.info("product_export_start")

    wb = Workbook(write_only=True)
    ws = wb.create_sheet("Products")

    ws.sheet_properties.tabColor = "1E3A5F"
    ws.freeze_panes = f"A{_DATA_START}"
    ws.row_dimensions[1].height = 34

    for col_idx, col in enumerate(PRODUCT_IMPORT_EXPORT_COLUMNS, start=1):
        ws.column_dimensions[get_column_letter(col_idx)].width = col.width

    _write_header_row(ws)

    rows_written = 0
    for raw_row in export_q.yield_per(_CHUNK_SIZE):
        rows_written += 1
        row_dict = _row_to_dict(raw_row, rate)
        _write_data_row(ws, rows_written, row_dict, is_odd=(rows_written % 2 == 1))

    logger.info("product_export_complete rows_written=%d", rows_written)

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf, rows_written
