# Generated by Django 6.0.3 on 2026-03-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBehaviorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_message', models.TextField(default='Hello! How can I help you today?')),
                ('closing_message', models.TextField(default='Thanks for chatting! Have a great day.')),
                ('tone', models.CharField(choices=[('friendly', 'Friendly & Warm'), ('professional', 'Professional'), ('sales', 'Sales-Oriented')], default='friendly', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
