# Generated by Django 6.0 on 2026-03-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaConfig',
        ),
    ]
