# Generated by Django 6.0 on 2026-04-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_delete_metaconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='media_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('sticker', 'Sticker'), ('location', 'Location')], default='text', max_length=20),
        ),
    ]
