# Generated by Django 6.0.3 on 2026-04-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_alter_conversationmessage_media_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ['-timestamp']},
        ),
    ]
