# Generated by Django 6.0 on 2026-05-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_alter_conversationmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='recipient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
